house_pricing:
  train_dataset: C:\Projects\ai_fundamentals\spbu-ai-fundamentals
  #test_dataset: D:\data\spbu_ai_fundamentals\house_prices\test.csv
#classification:
  #wdbc: D:\data\spbu_ai_fundamentals/classification/data.csv
  #mushrooms: D:\data\spbu_ai_fundamentals/classification/mushrooms.csv
#clustering:
  #flowcytometry: D:\data\spbu_ai_fundamentals/flow_cytometry
